---
- name: Execute CKA Lab Scenario - Initial Steps Reminder MOTD (motd)
  ansible.builtin.include_tasks: scenario_motd.yml
  when: cka_lab_scenario_motd_enabled | bool
  tags:
    - cka_lab
    - motd

- name: Execute CKA Lab Scenario - User Authentication & RBAC (user_rbac)
  ansible.builtin.include_tasks: scenario_user_rbac.yml
  when: cka_lab_scenario_user_rbac_enabled | bool
  tags:
    - cka_lab
    - user_rbac

- name: Execute CKA Lab Scenario - Sample Secrets (secrets)
  ansible.builtin.include_tasks: scenario_secrets.yml
  when: cka_lab_scenario_secrets_enabled | bool
  tags:
    - cka_lab
    - secrets

- name: Execute CKA Lab Scenario - Sample ConfigMaps (configmaps)
  ansible.builtin.include_tasks: scenario_configmaps.yml
  when: cka_lab_scenario_configmaps_enabled | bool
  tags:
    - cka_lab
    - configmaps

- name: Execute CKA Lab Scenario - Helm Tools & Monitoring (helm)
  ansible.builtin.include_tasks: scenario_helm.yml
  when: cka_lab_scenario_helm_enabled | bool
  tags:
    - cka_lab
    - helm

- name: Execute CKA Lab Scenario - NFS & Storage Volumes (volumes)
  ansible.builtin.include_tasks: scenario_volumes.yml
  when: cka_lab_scenario_volumes_enabled | bool
  tags:
    - cka_lab
    - volumes
    - nfs

- name: Execute CKA Lab Scenario - Deployments & ReplicaSets (deployments)
  ansible.builtin.include_tasks: scenario_deployments.yml
  when: cka_lab_scenario_deployments_enabled | bool
  tags:
    - cka_lab
    - deployments
    - workloads

- name: Execute CKA Lab Scenario - Pods & Namespaces (pods)
  ansible.builtin.include_tasks: scenario_pods.yml
  when: cka_lab_scenario_pods_enabled | bool
  tags:
    - cka_lab
    - pods
    - workloads
