# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX_IMAGE = ENV.fetch("BOX_IMAGE", "cloud-image/ubuntu-26.04")
WORKER_COUNT = ENV.fetch("WORKER_COUNT", "1").to_i
K8S_VERSION = ENV.fetch("K8S_VERSION", "1.34.1-1.1")

Vagrant.configure("2") do |config|
  config.vm.box = BOX_IMAGE

  # Ensure default SSH shell is bash
  config.ssh.shell = "bash -l"

  config.vm.synced_folder ".", "/vagrant", type: "9p", disabled: false, accessmode: "squash"

  config.vm.define "kube-control-plane" do |node|
    node.vm.hostname = "kube-control-plane"
    node.vm.network :private_network, ip: "192.168.56.10"

    node.vm.provider :libvirt do |lv|
      lv.driver = "kvm"
      lv.memory = 2048
      lv.cpus = 2
    end

    node.vm.provision "file", source: "scripts/cni-install-cilium.sh", destination: "/home/vagrant/cni-install-cilium.sh"
    node.vm.provision "file", source: "scripts/cni-install-calico.sh", destination: "/home/vagrant/cni-install-calico.sh"
    node.vm.provision "shell", inline: "chmod +x /home/vagrant/cni-install-*.sh && chown vagrant:vagrant /home/vagrant/cni-install-*.sh"

    node.vm.provision "shell", path: "scripts/common.sh", env: { "K8S_VERSION" => K8S_VERSION }
  end

  (1..WORKER_COUNT).each do |i|
    config.vm.define "kube-worker-#{i}" do |node|
      node.vm.hostname = "kube-worker-#{i}"
      node.vm.network :private_network, ip: "192.168.56.#{i + 20}"

      node.vm.provider :libvirt do |lv|
        lv.driver = "kvm"
        lv.memory = 2048
        lv.cpus = 2
      end

      node.vm.provision "shell", path: "scripts/common.sh", env: { "K8S_VERSION" => K8S_VERSION }
    end
  end

  config.vm.provision "shell",
    run: "always",
    inline: <<-SHELL
      chsh -s /bin/bash vagrant || usermod -s /bin/bash vagrant
      swapoff -a
    SHELL
end
