[control_plane]
# k8s-cp-01 ansible_host=10.0.10.10 node_ip=10.0.10.10

[workers]
# k8s-worker-01 ansible_host=10.0.10.21 node_ip=10.0.10.21
# k8s-worker-02 ansible_host=10.0.10.22 node_ip=10.0.10.22

[k8s_cluster:children]
control_plane
workers

[prod:children]
k8s_cluster

[k8s_cluster:vars]
ansible_user=xeno
ansible_python_interpreter=/usr/bin/python3
