[control_plane]
kube-control-plane ansible_host=192.168.56.10 node_ip=192.168.56.10 ansible_ssh_private_key_file="{{ inventory_dir }}/../../.vagrant/machines/kube-control-plane/libvirt/private_key"

[workers]
kube-worker-1 ansible_host=192.168.56.21 node_ip=192.168.56.21 ansible_ssh_private_key_file="{{ inventory_dir }}/../../.vagrant/machines/kube-worker-1/libvirt/private_key"
kube-worker-2 ansible_host=192.168.56.22 node_ip=192.168.56.22 ansible_ssh_private_key_file="{{ inventory_dir }}/../../.vagrant/machines/kube-worker-2/libvirt/private_key"

[k8s_cluster:children]
control_plane
workers

[preprod:children]
k8s_cluster

[k8s_cluster:vars]
ansible_user=vagrant
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes'
ansible_python_interpreter=/usr/bin/python3
