---
- name: Check if user exists on target
  ansible.builtin.getent:
    database: passwd
    key: "{{ current_admin_user }}"
  failed_when: false
  register: control_plane_user_check

- name: Setup user kubeconfig
  when: control_plane_user_check.ansible_facts.getent_passwd[current_admin_user] is defined and current_admin_user != 'root'
  block:
    - name: Get user home directory
      ansible.builtin.set_fact:
        control_plane_user_home: "{{ control_plane_user_check.ansible_facts.getent_passwd[current_admin_user][4] }}"

    - name: Create user .kube directory
      ansible.builtin.file:
        path: "{{ control_plane_user_home }}/.kube"
        state: directory
        owner: "{{ current_admin_user }}"
        group: "{{ current_admin_user }}"
        mode: '0700'

    - name: Copy kubeconfig for user
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: "{{ control_plane_user_home }}/.kube/config"
        remote_src: true
        owner: "{{ current_admin_user }}"
        group: "{{ current_admin_user }}"
        mode: '0600'
