---
control_plane_tools_k9s_version: "{{ k9s_version | default('v0.51.0') }}"
control_plane_tools_k9s_skin: "{{ k9s_skin | default('nord') }}"
control_plane_tools_etcd_version: "{{ etcd_version | default('v3.5.16') }}"
control_plane_tools_helm_apt_repo: >-
  {{ helm_apt_repo | default('deb [signed-by=/etc/apt/keyrings/helm.gpg] https://packages.buildkite.com/helm-linux/helm-debian/any/ any main') }}
control_plane_tools_helm_apt_key_url: "{{ helm_apt_key_url | default('https://packages.buildkite.com/helm-linux/helm-debian/gpgkey') }}"
control_plane_tools_helm_apt_key_fingerprint: >-
  {{ helm_apt_key_fingerprint | default('DDF78C3E6EBB2D2CC223C95C62BA89D07698DBC6') }}  # gitleaks:allow
control_plane_tools_user: "{{ ansible_user | default('vagrant') }}"
