---
# Handlers for cks_lab role
- name: Reload containerd
  ansible.builtin.systemd:
    name: containerd
    state: reloaded
  listen: "reload containerd"

- name: Restart kubelet
  ansible.builtin.systemd:
    name: kubelet
    state: restarted
  listen: "restart kubelet"
